message("src: CMAKE_CURRENT_LIST_DIR   = ${CMAKE_CURRENT_LIST_DIR}")
message("src: CMAKE_CURRENT_LIST_FILE  = ${CMAKE_CURRENT_LIST_FILE}")
message("src: CMAKE_CURRENT_LIST_LINE  = ${CMAKE_CURRENT_LIST_LINE}")